### ISSUE TITLE
0.0.4 is empty

### ISSUE THREAD

**Issue by halkeye** [mixtur/webpack-spritesmith#1]
something went wrong between 0.0.3 and 0.0.4

 $ curl -s http://registry.npmjs.org/webpack-spritesmith/-/webpack-spritesmith-0.0.4.tgz | tar tvz
-rw-rw-r-- 1000/1000       920 2016-01-28 08:23 package/package.json
-rw-rw-r-- 1000/1000        11 2015-11-26 08:49 package/.npmignore
 $ curl -s http://registry.npmjs.org/webpack-spritesmith/-/webpack-spritesmith-0.0.3.tgz | tar tvz
-rw-rw-r-- 1000/1000       920 2015-11-30 04:14 package/package.json
-rw-rw-r-- 1000/1000      3609 2015-11-30 04:13 package/Readme.md
-rw-rw-r-- 1000/1000      3824 2015-11-30 04:15 package/lib/Plugin.js
-rw-rw-r-- 1000/1000      1649 2015-11-26 08:14 package/lib/processOptions.js

**Comment by halkeye** [comment]
it looks like your .npmignore got a `*` in it

**Comment by halkeye** [comment]
actually it looks like the `*` has been there a while, so no idea whats wrong.

**Comment by mixtur** [comment]
Yeah, npm does that sometimes.
Have no idea why it happens. unpublish-publish usually helps. Just republished it as 0.0.5. Seems like it is ok now.
