### ISSUE TITLE
If you can customize the template is perfect

### ISSUE THREAD

**Issue by 3Q-** [mixtur/webpack-spritesmith#10]
css output style  i like this
.demo1, demo2, demo4{
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHQAAAB0CAMAAABjROYVAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyJpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoV2luZG93cykiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MzRBMTUzOEE5RDU1MTFFNTg5MEZDQjgyRkEzQzhFODEiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6MzRBMTUzOEI5RDU1MTFFNTg5MEZDQjgyRkEzQzhFODEiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDozNEExNTM4ODlENTUxMUU1ODkwRkNCODJGQTNDOEU4MSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDozNEExNTM4OTlENTUxMUU1ODkwRkNCODJGQTNDOEU4MSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pl2hm60AAADAUExURWd02u/z9PH09XJx2olt2pVr26mttbjC7OTm6c+v6q1m21112qyy6Pz9/q6T4+nn9/X4+ImOmHaO39PW2o+a4mhuelJZaHN5heXV8/n6/Fd32t3h7p9p29fW87m8w/T29/r8/);
}
.demo1 {
  background-position: -36px -68px;
  width: 36px;
  height: 30px;
}
.demo2 {
  background-position: -36px -68px;
  width: 36px;
  height: 30px;
}
.idemo4 {
  background-position: -36px -68px;
  width: 36px;
  height: 30px;
}
-------------------------------------------------------------
so bad like this:
.demo1 {
background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHQAAAB0CAMAAABjROYVAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyJpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoV2luZG93cykiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MzRBMTUzOEE5RDU1MTFFNTg5MEZDQjgyRkEzQzhFODEiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6MzRBMTUzOEI5RDU1MTFFNTg5MEZDQjgyRkEzQzhFODEiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDozNEExNTM4ODlENTUxMUU1ODkwRkNCODJGQTNDOEU4MSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDozNEExNTM4OTlENTUxMUU1ODkwRkNCODJGQTNDOEU4MSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pl2hm60AAADAUExURWd02u/z9PH09XJx2olt2pVr26mttbjC7OTm6c+v6q1m21112qyy6Pz9/q6T4+nn9/X4+ImOmHaO39PW2o+a4mhuelJZaHN5heXV8/n6/Fd32t3h7p9p29fW87m8w/T29/r8/);
  background-position: -36px -68px;
  width: 36px;
  height: 30px;
}
.demo2 {
background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHQAAAB0CAMAAABjROYVAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyJpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoV2luZG93cykiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MzRBMTUzOEE5RDU1MTFFNTg5MEZDQjgyRkEzQzhFODEiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6MzRBMTUzOEI5RDU1MTFFNTg5MEZDQjgyRkEzQzhFODEiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDozNEExNTM4ODlENTUxMUU1ODkwRkNCODJGQTNDOEU4MSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDozNEExNTM4OTlENTUxMUU1ODkwRkNCODJGQTNDOEU4MSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pl2hm60AAADAUExURWd02u/z9PH09XJx2olt2pVr26mttbjC7OTm6c+v6q1m21112qyy6Pz9/q6T4+nn9/X4+ImOmHaO39PW2o+a4mhuelJZaHN5heXV8/n6/Fd32t3h7p9p29fW87m8w/T29/r8/);
  background-position: -36px -68px;
  width: 36px;
  height: 30px;
}
.demo4 {
background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHQAAAB0CAMAAABjROYVAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyJpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoV2luZG93cykiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MzRBMTUzOEE5RDU1MTFFNTg5MEZDQjgyRkEzQzhFODEiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6MzRBMTUzOEI5RDU1MTFFNTg5MEZDQjgyRkEzQzhFODEiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDozNEExNTM4ODlENTUxMUU1ODkwRkNCODJGQTNDOEU4MSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDozNEExNTM4OTlENTUxMUU1ODkwRkNCODJGQTNDOEU4MSIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pl2hm60AAADAUExURWd02u/z9PH09XJx2olt2pVr26mttbjC7OTm6c+v6q1m21112qyy6Pz9/q6T4+nn9/X4+ImOmHaO39PW2o+a4mhuelJZaHN5heXV8/n6/Fd32t3h7p9p29fW87m8w/T29/r8/);
  background-position: -36px -68px;
  width: 36px;
  height: 30px;
}

**Comment by mixtur** [comment]
I assume you are using plain css as your target, and url-loader right?
If that is your case, then you could probably use this https://github.com/twolfson/spritesheet-templates#custom
In webpack config it would look roughly like this:

```javascript
var templater = require('spritesheet-templates');
templater.addTemplate('your_format', /*some template function here*/);
...
module.exports = {
  plugins: [
    ...
    new SpritesmithPlugin({
      ...
      target: {
      css: [['yourcss.css', {
          format: 'your_format'
      }]]
    })
  ]
}
```

I haven't checked that myself but it should work.

**Comment by 3Q-** [comment]
@mixtur  thanks!

**Comment by mixtur** [comment]
Sorry I still had no time to check this myself.
Does that helped?

**Comment by yonatan-bin** [comment]
hi, 
while using grunt i can define a handlebar template as source. 
how can i configure this in this plugin? 

thanks.
John.

**Comment by mixtur** [comment]
I finally checked it. Yes it is working. Closing now.

**Comment by pmendozav** [comment]
Hi,
@mixtur If you have an example using plain-css as target I will be so grateful, I am new using webpack and I am not sure how to use custom templates right.

**Comment by mixtur** [comment]
I don't have one, um, I can create a folder with examples in this repo. But not in nearest two days, sorry.
In the mean time you'll simply have to specify .css extension in `target.css` in plugin config. 
```js
{
  target: {
    css: 'path/to/api/you/want/to/generate.css'
  }
}
```
