### ISSUE TITLE
generate two sass files has

### ISSUE THREAD

**Issue by 3Q-** [mixtur/webpack-spritesmith#13]
When I generate two sass files  ico.scss and icon1.scss, the defined variables are the same, I will fail import them at page.scss;

`new SpritesmithPlugin(spritesmithOpts('ico'))
scss contents:
$spritesheet-width: 35px;
$spritesheet-height: 32px;
$spritesheet-image: '~sprites/ico.png';
$spritesheet-sprites: ($ico-demodemo, $ico-hover-hover-ico-hover-hover, $ico-hover, );
$spritesheet: (35px, 32px, '~sprites/ico.png', $spritesheet-sprites, );

new SpritesmithPlugin(spritesmithOpts('ico1')),
scss contents:
$spritesheet-width: 122px;
$spritesheet-height: 98px;
$spritesheet-image: '~sprites/ico1.png';
$spritesheet-sprites: ($ico1-hover-hover-ico1-hover-hover, $ico1-hover-hover-2x, $ico1-hover, $ico1-hover-2x, $ico1-hover-hover, $ico1-hover-hover-2x, $ico1-normal, $ico1-normal-2x, $ico1-red, $ico1-red1, $ico1-red1-2x, $ico1-red-2x, $ico1-turquoise, $ico1-turquoise-2x, );
$spritesheet: (122px, 98px, '~sprites/ico1.png', $spritesheet-sprites, );
`

Can you update your files compileNormal.js line 35 like this

   function toSpritesheetTemplatesFormat(spritesmithResult) {
        var generateSpriteName = options.apiOptions.generateSpriteName;
        var sprites = _.map(
            spritesmithResult.coordinates,
            function (oneSourceInfo, fileName) {
                return _.extend(
                    {name: generateSpriteName(fileName)},
                    oneSourceInfo
                );
            }
        );

        var spritesheet = _.extend(
            {image: options.apiOptions.cssImageRef},
            spritesmithResult.properties
        );

        return {
            sprites: sprites,
            spritesheet: spritesheet,
           // add an identifier  thanks a lot
            spritesheetName:options.spritesheetName
        };
    }

**Comment by mixtur** [comment]
you can do this

```javascript
new SpritesmithPlugin({
  target: {
    css: [['/path/to/ico1.scss', { spritesheetName: 'ico-1' }]]
    ...
  }
  ...
})

new SpritesmithPlugin({
  target: {
    css: [['/path/to/ico2.scss', { spritesheetName: 'ico-2' }]]
    ...
  }
  ...

```

**Comment by 3Q-** [comment]
Thanks a lot
