### ISSUE TITLE
Include hash in generated file

### ISSUE THREAD

**Issue by prabirshrestha** [mixtur/webpack-spritesmith#17]
Is it possible to include hash in generated sprite PNG? Setting the filename to "sprite.[hash].PNG" doesn't work.

**Comment by mixtur** [comment]
Will be possible in the next version. Currently I would suggest to use file-loader and css-loader.

**Comment by mixtur** [comment]
it should work in 0.2.6 though you'll have to use the same naming schema in `apiOptions.cssImageRef`. Closing this for now.

**Comment by Droritos** [comment]
Using version 0.2.6, only [hash] is supported, while [hash**:8**] for example is not.

Can you please include support for limiting the hash size ?

**Comment by Asing1001** [comment]
I just tried `sprite.[hash:7].png` and it works
