### ISSUE TITLE
empty sprite

### ISSUE THREAD

**Issue by joemidi** [mixtur/webpack-spritesmith#21]
Hey,

I've got the following config:

```
    webpackConfig.plugins.push(new SpritesmithPlugin({
      src: {
        cwd: pathString + '/' + key + '/images/sprites',
        glob: '*.png'
      },
      target: {
        image: path.join(pathString, key, 'images', 'generated', 'sprite.png'),
        css: path.join(pathString, key, 'css', 'generated', '_sprites.scss')
      },
        apiOptions: {
        cssImageRef: '/' + key + '/images/generated/sprite.png'
      }
    }));
```

Which works great when I have a sprites folder and need things made into a sprite. However, in the case where I'm not using a sprites folder, it still generates an empty sprite.

Is there a way to check if the cwd path actually has something inside before processing?

**Comment by joemidi** [comment]
nvm!

I wrapped it in a fs.stat and promised it.

```
    new Promise(function(resolve, reject) {
      var status = fs.statSync(pathString + '/' + key + '/images/sprites');
      resolve(status && status.isDirectory());
    })
    .then(function(val) {
      webpackConfig.plugins.push(new SpritesmithPlugin({
        src: {
          cwd: pathString + '/' + key + '/images/sprites',
          glob: '*.png'
        },
        target: {
          image: path.join(pathString, key, 'images', 'generated', 'sprite.png'),
          css: path.join(pathString, key, 'css', 'generated', '_sprites.scss')
        },
          apiOptions: {
          cssImageRef: '/' + key + '/images/generated/sprite.png'
        }
      }));
    })
    .catch(function(err) {
      gutil.log(err)
    });
```

**Comment by mixtur** [comment]
Uhh... ok.
I can not imagine the situation where you don't know ahead of time if you have any sprite sources or not. 
Can you tell more about your case?

**Comment by joemidi** [comment]
I'm working on a project that produces multiple stand-alone builds depending on the target dimensions.

Sometimes it's not required to have a sprite sheet for the elements because the number of images has been greatly reduced, or it's just inappropriate.

Wrapping it in a `fs.stat` check allows me to first check if the sprite directory even exists before wasting time and resources trying to sprite sheet non-existent images.
