### ISSUE TITLE
Use `loader-utils` with `interpolateName` for support all properties in name

### ISSUE THREAD

**Issue by evilebottnawi** [mixtur/webpack-spritesmith#22]
Example: i need feature `[<hashType>:hash:<digestType>:<length>]`. Thanks!

**Comment by mixtur** [comment]
Sorry. I really don't have time at the moment. Though I'll look at it in a week or two.
You are welcome to fork and do it yourself If you don't want to wait that much.
I am accepting PRs.

**Comment by mixtur** [comment]
Also "loader-utils" and "interpolateName" are not really applicable there since webpack-spritesmith is not a loader. It is a plugin. Still, I'll see what I can do.

**Comment by evilebottnawi** [comment]
@mixtur `loader-utils` have some feature what can be using not only for `loaders`. Thanks. If I find time, I do PRю

**Comment by mixtur** [comment]
should work  in 0.3.0
