### ISSUE TITLE
Wrong path to images in version 0.3.0

### ISSUE THREAD

**Issue by niclassparr** [mixtur/webpack-spritesmith#24]
Seems like this issue is back in version 0.3.0
https://github.com/mixtur/webpack-spritesmith/issues/7

With 
        apiOptions: {
            cssImageRef: '**src/img/sprite.png**'
        }
I get 
$arrow-left: (764px, 490px, -764px, -490px, 53px, 105px, 1489px, 1067px, '**src/img\sprite.png**', 'arrow_left', );

I use
Windows 10
webpack 2.1.0-beta.27
node v6.9.1
npm 3.10.8

It works fine in version 0.2.6

**Comment by mixtur** [comment]
The same mistake, te same solution. Thank you for reporting) 0.3.1 should be ok.

**Comment by niclassparr** [comment]
Excellent!

Thanks for the superfast fix ☺

/Niclas

**Comment by anonrig** [comment]
This is still an issue. I'm getting the same error, and sprite.png is not found because on the loader the file name is changed. Are there any fix on this?

**Comment by mixtur** [comment]
What do you mean "the file name is changed"? What it was and what it became?
