### ISSUE TITLE
Keep getting cannot find ~/sprite.scss

### ISSUE THREAD

**Issue by anonrig** [mixtur/webpack-spritesmith#26]
I'm receiving this error:

```
Error in ./src/components/header/style.scss
Module build failed: 
@import '~sprite.scss';
^
      File to import not found or unreadable: ~sprite.scss.
Parent style sheet: stdin

```
My webpack loaders are:

      {
        test: /\.scss$/,
        include: paths.appSrc,
        loaders: ['style', "css", "sass"]
      },
      {
        test: /\.png$/,
        loaders: [
          'file?name=i/[hash].[ext]'
        ]
      },

My plugins are:

    new SpritesmithPlugin({
      src: {
        cwd: path.resolve(__dirname, '../src/images/sprites'),
        glob: '*.png'
      },
      target: {
        image: path.resolve(__dirname, '../src/images/sprite.png'),
        css: path.resolve(__dirname, '../src/images/sprite.scss')
      },
      apiOptions: {
        cssImageRef: "~sprite.png"
      }
    }),

**Comment by mixtur** [comment]
Do you have `resolve` configured in webpack?

for your case it should be something like this, I think
```javascript
resolve: {
      modulesDirectories: ["node_modules", "images"]
}
```

or maybe 

```javascript
resolve: {
      alias: {
          'sprite': path.resolve(__dirname, '../src/images/sprite.scss')
      }
}
```

**Comment by mixtur** [comment]
So... Is that your case? Did it helped?

**Comment by stefanfrede** [comment]
@mixtur Your solution worked for me :)
