### ISSUE TITLE
Object.extend is not a function  in compileNormal.js

### ISSUE THREAD

**Issue by belowfrog** [mixtur/webpack-spritesmith#28]
webpack throw this error:
<img width="629" alt="xxxx" src="https://cloud.githubusercontent.com/assets/14297829/23602735/dac5dabc-028c-11e7-9bc4-d8dc4eee0342.png">

**Comment by yvele** [comment]
Yep, same problem for me..

**Comment by mixtur** [comment]
Quick workaround - update node.js.
Will fix it as soon as I'll return home (11 hours from now)

**Comment by mixtur** [comment]
Oh I see) Updating node won't help. Sorry. I'll fix it anyway later today.

**Comment by yvele** [comment]
Workarround: Switch back to `0.3.1` 😉

**Comment by yvele** [comment]
You can maybe unpublish `0.3.1` from npm or mark it as deprecated
