### ISSUE TITLE
Retina Sprites

### ISSUE THREAD

**Issue by jbrialon** [mixtur/webpack-spritesmith#3]
Hello,

how could I configure webpack-spritesmith to generate retina sprites ? (@2x)
I can't figure how to pass the right parameters

thanks in advance

**Comment by mixtur** [comment]
I believe you currently can't. I'll investigate the way retina sprites are handled in spritesheet-templates in nearest few days and implement this feature then.

**Comment by jbrialon** [comment]
thanks :+1:

**Comment by mixtur** [comment]
I think I implemented it. I will not publish for a few more days just in case if I ocasionally broke something in process. It is not really tested yet.
But you can try it with `npm i github:mixtur/webpack-spritesmith#retina`.
To enable retina mode just add `retina: '@2x'` to config.

**Comment by jbrialon** [comment]
I just tried and it seems to work fine, I let you now if I encounter some issues

thanks a lot !

**Comment by alettieri** [comment]
+1 This is great

**Comment by mixtur** [comment]
published to npm

**Comment by alettieri** [comment]
@mixtur great!

**Comment by bennam** [comment]
Will this support '@3x'?

**Comment by mixtur** [comment]
@bennam There is a problem with that.
webpack-spritesmith works in two steps. Generating spritesheet image and generating API in SASS/LESS/etc.

So I can generate any number of spritesheets by some criterion. But when generarating API I rely on this library https://github.com/twolfson/spritesheet-templates and it only support 1x and 2x sprites.
