### ISSUE TITLE
Scss image path

### ISSUE THREAD

**Issue by GuillaumeKadolis** [mixtur/webpack-spritesmith#31]
Hello,

i want override my sprite path 
`$picto-image: '../img/sprite.png';`
to
`$picto-image : '../../../assets/img/sprite.png'`

but $*-image var aren't used

into sprite.scss
`$picto-image: '../img/sprite.png';`
`$picto: (0px, 0px, 0px, 0px, 282px, 301px, 564px, 301px, '../img/sprite.png', 'picto', );`

should be 

`$picto-image: '../img/sprite.png';`
`$picto: (0px, 0px, 0px, 0px, 282px, 301px, 564px, 301px, $picto-image, 'picto', );`

why do you use diff var for same path ? 
`$picto-image: '../img/sprite.png';`
`$logo-image: '../img/sprite.png';`
`$quadrillage-image: '../img/sprite.png';`
`$spritesheet-image: '../img/sprite.png';`

**Comment by mixtur** [comment]
I am not) it is [spritesheet-templates](https://github.com/twolfson/spritesheet-templates/blob/master/lib/templates/sass.template.handlebars#L30)

I think it is easier to override mixin `sprite-image` in your case.

Also You can write your own template where you'll be able to override whatever you want.

**Comment by GuillaumeKadolis** [comment]
thank you for your answer I do not find it very logical to override a mixin instead a variable, write a template is the best option.
