### ISSUE TITLE
what does `~`  in cssImageRef: "~sprite.png" mean？

### ISSUE THREAD

**Issue by antwang** [mixtur/webpack-spritesmith#34]
hi mixtur ,i am confused about your example ：
```
resolve: {
        //webpack 1:
        modulesDirectories: ["node_modules", "spritesmith-generated"],
        //webpack 2:
        modules: ["node_modules", "spritesmith-generated"]
    }, 
```
and
```
apiOptions: {
    cssImageRef: "~sprite.png"
}
```
1.what does `~`  in cssImageRef: "~sprite.png" mean?
2. is `spritesmith-generated`  related to `~sprite.png` or `~`?

Looking forward to your reply
thx

**Comment by mixtur** [comment]
Yes it is all related. `~`  is from css-loader. It means "let webpack find that file".
 In readme I assume that sass/less/whatever may appear in different (multiple) places inside your project's folder structure, therefore relative path cannot be used. So, you can either try absolute path, or webpack's resolution mechanism.
I choose the former. To make it work you have to configure resolve section in webpack config. Then webpack can find these files by short names like `~something.png`.
In example I put generated files to a folder that is then specified in`resolve` section, so webpack can find them there when they are required via ~.

**Comment by mixtur** [comment]
1. `~modulename` is webpack convention for requiring modules from languages with their own module system when you want to use webpack's resolving mechanism. For example you could
```css
@import "~bootstrap/css/bootstrap.css"
```
 from some css file, given that bootstrap is installed in `node_modules`.

2. `resolve.modules` - is a tweak for webpack module system, that makes webpack look for modules not only in "node_modules" but also in "spritesmith-generated". So if there is "spritesmith-generated/sprite.png" somewhere close to root of your project, webpack will find it when you do `require('~sprite.png')` in js or `url(~sprite.png)` in css. So answering your question `spritesmith-generated` is related to both `~` and `~sprite.png`.

**Comment by yangbin1994** [comment]
i get it ~thx
