### ISSUE TITLE
The config 'glob' does not  work with `**`

### ISSUE THREAD

**Issue by linguochi** [mixtur/webpack-spritesmith#35]
my config for this plugin is
 ``` javascript
plugins: [
    new SpritesmithPlugin({
      // 目标小图标
      src: {
        cwd: path.resolve(__dirname, '../src/assets/icons'),
        glob: '{**.png,**.jpg}'
      },
      // 输出雪碧图文件及样式文件
      target: {
        image: path.resolve(__dirname, '../src/assets/sprite/sprite.png'),
        css: path.resolve(__dirname, '../src/assets/sprite/sprite.css')
      },
      // 样式文件中调用雪碧图地址写法
      apiOptions: {
        cssImageRef: './sprite.png'
      },
      spritesmithOptions: {
        algorithm: 'top-down'
      }
    })
  ]
```

and my directories are
![image](https://cloud.githubusercontent.com/assets/15223697/26143353/30a3e04c-3b17-11e7-8b1b-0450b5c1539f.png)

each  subdirectory  has some .png files。 But it seem to  only  cope with the files in the first directory.

**Comment by mixtur** [comment]
Try '**/*.{png,jpg}'

**Comment by mixtur** [comment]
Also note that only directories that exists at the moment of webpack startup will be used. New directories will only be taken into account after restart of webpack. I am not sure why that is happening but it is the way [gaze](https://github.com/shama/gaze) works.

**Comment by linguochi** [comment]
@mixtur  It works for me.  Thank you!
