### ISSUE TITLE
no sprite image produced?

### ISSUE THREAD

**Issue by MarvinXu** [mixtur/webpack-spritesmith#37]
anything wrong?
https://github.com/MarvinXu/spritesmith-test

**Comment by mixtur** [comment]
Looks fine at first sight. I'll try to dig deeper when I got home

**Comment by mixtur** [comment]
ok. I figured it out.
1. You are incorrectly using your helper `resolve` when configuring `src.cwd`. It should be one argument, not two.
2. You have incorrect glob in `src.glob`. You are matching immediate children of src/app, but in your directory structure sprite source images are actually deeper, so it should be something like `**/sprites/*.png`.
3. You did not specified `apiOptions: {cssImageRef: '~home-sprite.png'}`. Without that in generated scss generated files are referenced by their absolute paths, which probably will not work.
Fix these and it should work.

**Comment by MarvinXu** [comment]
It worded! Thanks for the patience, appreciated it!
