### ISSUE TITLE
Regenerated sprite.png and sprite.styl/sass/less in runtime

### ISSUE THREAD

**Issue by stephanedemotte** [mixtur/webpack-spritesmith#4]
Hi !

Thanks a lot for your work!

One question,  if i add a new sprite, webpack failed to get the new sprite because `sprite.png` and `sprite.styl` are not updated.

I have to kill the process and run it again.

Do you think, we can keep alive the webpack process while the new sprite is generated ?

Sorry my english suck.

Thanks !

**Comment by mixtur** [comment]
Let's make sure we are talking about the same thing.

What you saying is:
You start webpack in watch mode
then you add some source image, and generated sprite is not getting updated after that, right?

I never experienced exactly that, though if I create new directory and THEN put there new source file, then yes, I'll have to restart webpack to hook up new directory.

What is your config?

**Comment by stephanedemotte** [comment]
Humm damn you'r right, if the folder already exist, yes, generated sprite is RE-generate.

So sorry for consuming your time 

And thanks again !
