### ISSUE TITLE
Webpack compiles the same files several times after starting

### ISSUE THREAD

**Issue by g1un** [mixtur/webpack-spritesmith#40]
Hie!
Webpack compiles the same files several times after starting. It looks like infinite looping. Can you please look my config (https://github.com/g1un/webpack-learn/blob/master/webpack.config.js) and say what's wrong?

For example:
webpack: Compiled successfully.
webpack: Compiling...
Hash: 271faba491d182ab12cc
Version: webpack 3.0.0
Time: 30ms
         Asset       Size  Chunks             Chunk Names
img/sprite.png     109 kB          [emitted]  
      main.css  451 bytes       0  [emitted]  app
    index.html  889 bytes          [emitted]  
  [86] ./src/css/main.scss 41 bytes {0} [built]
    + 88 hidden modules
Child html-webpack-plugin for "index.html":
       2 modules
Child extract-text-webpack-plugin:
             Asset    Size  Chunks             Chunk Names
    img/sprite.png  109 kB          [emitted]  
       [0] ./src/img/sprite/sprite.png 60 bytes {1} [built]
       [1] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/css/main.scss 698 bytes {1} [built]
        + 1 hidden module
webpack: Compiled successfully.
webpack: Compiling...
Hash: 9aa5a8f6c5fc5f52c538
Version: webpack 3.0.0
Time: 42ms
         Asset       Size  Chunks             Chunk Names
img/sprite.png     109 kB          [emitted]  
      main.css  451 bytes       0  [emitted]  app
    index.html  889 bytes          [emitted]  
  [86] ./src/css/main.scss 41 bytes {0} [built]
    + 88 hidden modules
Child html-webpack-plugin for "index.html":
       2 modules
Child extract-text-webpack-plugin:
             Asset    Size  Chunks             Chunk Names
    img/sprite.png  109 kB          [emitted]  
       [0] ./src/img/sprite/sprite.png 60 bytes {0} [built]
       [1] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/css/main.scss 698 bytes {0} [built]
        + 1 hidden module
webpack: Compiled successfully.
webpack: Compiling...
Hash: 271faba491d182ab12cc
Version: webpack 3.0.0
Time: 29ms
         Asset       Size  Chunks             Chunk Names
img/sprite.png     109 kB          [emitted]  
      main.css  451 bytes       0  [emitted]  app
    index.html  889 bytes          [emitted]  
  [86] ./src/css/main.scss 41 bytes {0} [built]
    + 88 hidden modules
Child html-webpack-plugin for "index.html":
       2 modules
Child extract-text-webpack-plugin:
             Asset    Size  Chunks             Chunk Names
    img/sprite.png  109 kB          [emitted]  
       [0] ./src/img/sprite/sprite.png 60 bytes {1} [built]
       [1] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/css/main.scss 698 bytes {1} [built]
        + 1 hidden module
webpack: Compiled successfully.

Thanks.

**Comment by mixtur** [comment]
Glob seems to be wrong. Try `'*.(png|jpg)'`. Though it is still strange.

**Comment by mixtur** [comment]
kinda fixed in 0.3.5 But your glob is still wrong))
