### ISSUE TITLE
Multiple customTemplates functions

### ISSUE THREAD

**Issue by slaby93** [mixtur/webpack-spritesmith#50]
Hi there!

I have a case where I have to have multiple instances of SpritesmithPlugin for my webpack project. As Im refactoring huge legacy project ( basically moving it from compass + browserify + ruby asset_pipeline to webpack ) I have many strange requirements.
So Im working on icon sprites right now and we have edge case that for many different folders I need to have separate SpritesmithPlugin configurations. So I just add many times new SpritesmithPlugin and it works except for customTemplates. I need to have separate customTemplates functions for different instances but as I see, they are overwritten.
Is there any trick to use?

**Comment by GreenMashimaro** [comment]
I also encountered this problem.
I need to generate 2 sprites based on two different directories.
But these two sprites are different templates.
Problem: The problem is that the template for the second new SpritesmithPlugin will overwrite the template for the first new SpritesmithPlugin.
```
plugins: [
  new SpritesmithPlugin({
    customTemplates: {
      icon_template: function (data) {
        var shared = '.ico { background-image: url(I) }'
            .replace('I', data.sprites[0].image);

        var perSprite = data.sprites.map(function (sprite) {
          return '.ico-N { width: Wpx; height: Hpx; background-position: Xpx Ypx; }'
              .replace('N', sprite.name)
              .replace('W', sprite.width)
              .replace('H', sprite.height)
              .replace('X', sprite.offset_x)
              .replace('Y', sprite.offset_y);
        }).join('\n');

        return shared + '\n' + perSprite;
      }
    }
  }),
  new SpritesmithPlugin({
    customTemplates: {
      icon_template: function (data) {
        var shared = '.ico { background-image: url(I) }'
            .replace('I', data.sprites[0].image);

        var perSprite = data.sprites.map(function (sprite) {
          return '.ico-N { width: WPX; height: HPX; background-position: XPX YPX; }'
              .replace('N', sprite.name)
              .replace('W', sprite.width)
              .replace('H', sprite.height)
              .replace('X', sprite.offset_x)
              .replace('Y', sprite.offset_y);
        }).join('\n');

        return shared + '\n' + perSprite;
      }
    }
  })
]
```
