### ISSUE TITLE
how to make sprite with jpg?

### ISSUE THREAD

**Issue by overarchingSky** [mixtur/webpack-spritesmith#51]
I tried to make cssSprite with picture in JPG and PNG，but only PNG  work. It looks like JPG be ignored .
this is my configs:
`new SpritesmithPlugin({
      src: {
          cwd: path.resolve(__dirname, '../static/images'),
          glob: '*.png'
      },
      target: {
          image: path.resolve(__dirname, '../src/assets/images/sprite.png'),
          css: path.resolve(__dirname, '../src/assets/images/sprite.less')
      },
      apiOptions: {
          cssImageRef: "~sprite.png"
      }
    })`
I tried again to configure glob to ‘\*.\*’ and '*.jpg', but failed. 
How can I achieve this goal？thinks！

**Comment by overarchingSky** [comment]
ofter view at the source code, I discovered the project is beased on get-pixels，it seem like only support png，gif and jpej？

**Comment by mixtur** [comment]
Well. I can say as much as you are. Looks like pixelsmith supports jpeg as source image, so it should work. There shouldn't be anything in plugin source code that would bind it specifically to png. So if there is a any problem it is most likely not here.
How does your failure looks exactly?

**Comment by overarchingSky** [comment]
At first, I just wanted to  merge pictures in jpg and png, so, I configure  glob to '\*.\*',but got error with ‘SOI not found‘.

**Comment by mixtur** [comment]
So, *.jpg also doesn't work? Try `*.{jpg,png}`

**Comment by mixtur** [comment]
Quick googling suggests there is something wrong with your source images. Try reconvert your jpegs.

**Comment by mixtur** [comment]
Also if it will not help, you may try different engine. [gmsmith](https://github.com/twolfson/gmsmith) should be less picky on source files. Here is list of engines claimed to be supported by spritesmith https://github.com/Ensighten/spritesmith#engines. And here is how config would look like in your case

```js
new SpritesmithPlugin({
      src: {
          cwd: path.resolve(__dirname, '../static/images'),
          glob: '*.{jpg,png}'
      },
      spritesmithOptions: {
         engine: require('gmsmith')
      },
      target: {
          image: path.resolve(__dirname, '../src/assets/images/sprite.png'),
          css: path.resolve(__dirname, '../src/assets/images/sprite.less')
      },
      apiOptions: {
          cssImageRef: "~sprite.png"
      }
    })
```

**Comment by overarchingSky** [comment]
It's the same as you said that there is something wrong with my source images.
After replaced,it works as same as I  thought.
In addition, the question #52  get solved with the below config:
```
new SpritesmithPlugin({
      src: {
        cwd: path.resolve(__dirname, "../static/images"), 
        glob: "*.{jpg,png,gif,jpeg}"
      },
      target: {
        image: path.resolve(__dirname, "../static/sprite/sprite.png"),
        css: path.resolve(__dirname, "../src/less/sprite/sprite-png.less")
      },
      apiOptions: {
        cssImageRef: "../../../static/sprite/sprite.png"
      }
    })
```
thanks so much!
