### ISSUE TITLE
SendToPast

### ISSUE THREAD

**Issue by wind4gis** [mixtur/webpack-spritesmith#55]
I'm reading the code now, and I'm confused by the sendToPast.js , should we change then atime and mtime  to be 1s before?? why??

**Comment by mixtur** [comment]
It is an ugly workaround for [this](https://github.com/webpack/watchpack/issues/25) webpack's bug.

**Comment by yessky** [comment]
I'd recommend you a magic workaround [here](https://github.com/webpack/watchpack/issues/25#issuecomment-319292564)

**Comment by mixtur** [comment]
Huh. I'll try that. It definitely looks better then what I did.
