### ISSUE TITLE
Property "sprite" must be followed by a ':'

### ISSUE THREAD

**Issue by wzup** [mixtur/webpack-spritesmith#57]
Your plugin generates sprite and `.scss` all right. However, it throws if I follow your docs:

```
.close-button
    sprite($close)

Property "sprite" must be followed by a ':'
```

What is `sprite($close)` ? It is obviously not a valid `.scss` or `.css` property. What did you mean in your docs?

**Comment by mixtur** [comment]
Example was for stylus. In scss you do `@include sprite($close)` If I remember correctly.
