### ISSUE TITLE
empty module after install

### ISSUE THREAD

**Issue by fenos** [mixtur/webpack-spritesmith#6]
after `npm install webpack-spritesmith -D` it doesn't clone the lib folder, i think !/lib/* didn't work out any idea?

**Comment by mixtur** [comment]
Npm sometimes does that when I am switching between registries. I'll republish it as soon as I'll get to my computer.

**Comment by fenos** [comment]
@mixtur thanks, don't worry whenever you have a bit of time, i did forked the project for now :+1:

**Comment by mixtur** [comment]
just fixed it
