### ISSUE TITLE
Request: Allow to change "spritesheet-templates" cssSelector option on config

### ISSUE THREAD

**Issue by ejribeiro** [mixtur/webpack-spritesmith#63]
I would like to be able to configure cssSelector sent to "spritesheet-templates" on this plugin, instead of have to make my own template to avoid `'.icon-' + sprite.name` as my CSS selector.

This option is available on [retina](https://github.com/twolfson/spritesheet-templates#css_retina) and [non-retina](https://github.com/twolfson/spritesheet-templates#css) templates.

Thanks in advance ;)

**Comment by mixtur** [comment]
Ok now I realize the way I implemented it is very awkward. But yet.

You can do
```
target: {
  ...
  css: [['css', {
    cssSelector: whatever
  }]]
}
```

Does this solves your problem?

**Comment by ejribeiro** [comment]
Hey,
Thanks for your quick response.

I've tried your solution and did not worked. However it gave me some debug ideas and now I can send the cssSelector function if I put the following config:
```javascript
target: {
  ...
  css: [['path/to/css.css', {
    formatOpts: {
        cssSelector: (groupName) => `.sprite-custom-prefix${groupName}`
    }
  }]]
}
```

It's tricky, but the problem is not on your package, but on  `spritesheet-templates` - I've had to read their source and debug it to find a solution.

So I will close this issue.
Cheers

**Comment by mwoz123** [comment]
works for me:) but I'd to change 
```
(..)
cssSelector: (groupName) => `.sprite-custom-prefix${groupName}`
```
to 
```
(..)
 cssSelector: (sprite) => `.sprite-custom-prefix${sprite.name}`
```

otherwise it errors: 
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):     
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):  
SassError: Expected "]".                                                              
   ╷                                                                                  
19 │ .sprite-custom-prefix[object Object]{                                            
   │                              ^                                                   
   ╵                                                                                  
```
