### ISSUE TITLE
using retina '@2x' and padding, but only @1x image has padding

### ISSUE THREAD

**Issue by jinghaonode** [mixtur/webpack-spritesmith#69]
new SpritesmithPlugin({
      src: {
          cwd: path.resolve(__dirname, '../src/ico'), 
          glob: '*.png'
      },
      target: {
        image: path.resolve(__dirname, '../src/assets/sprite.png'),
        css: path.resolve(__dirname, '../src/assets/sprite.scss')
      },
      apiOptions: {
        cssImageRef: '~@/assets/sprite.png'
      },
      retina: '@2x',
      spritesmithOptions: {
        algorithm: 'top-down',
          padding: 20
    },
  })
![4165608](https://user-images.githubusercontent.com/12907388/43674481-4b36c958-9807-11e8-91e2-70bcf27aecad.png)

**Comment by mixtur** [comment]
should be fixed in 0.5.2
