### ISSUE TITLE
Wrong path with retina option on windows OS

### ISSUE THREAD

**Issue by fenos** [mixtur/webpack-spritesmith#7]
I enabled the retina option, and this are my full configuration of `webpack-spritesmit`

~~~js
new SpritesmithPlugin({
            src: {
                cwd: path.resolve(__dirname, '../static/sprites'),
                glob: '*.png'
            },
            target: {
                image: path.resolve(__dirname, '../static/img/sprites/iup_sprite.png'),
                css: path.resolve(__dirname, '../app/styles/sprite.scss'),

            },
            retina: '@2x',
            spritesmithOptions: {
                padding: 5
            },
            apiOptions: {
                cssImageRef: "../../../../static/img/sprites/iup_sprite.png",
            }
        }),
~~~

So the plugin works very nicely, but when it try to generate the retina image on a windows machine it give to the `sprite.scss` a wrong path as following:

~~~
$retina-small-play-btn-image: '../../../../static/img/sprites\iup_sprite@2x.png';
~~~

if you noticed the last slash is a `backslash` which is what windows use as path reference.

I spent a bit of time debugging the plugin and look for the cause, and i find out that the problem is given from the `path.format()` on `processOptions/addSuffixToFileName`. it seem that it process the path as the OS want, but of course css is not happy about it.

I did a quick fix in this way:

~~~js
function addSuffixToFileName(suffix, fileName) {
    var parsed = path.parse(fileName);
    parsed.name += suffix;
    parsed.base = parsed.name + parsed.ext;
    return parsed.dir + '/' + parsed.base; // Instead of using path.format()
}
~~~

Let me know if is my mistake on configuring the plugin, or if you'd like a PR about this issue.
Thanks a lots for the plugin anyway, very useful.

**Comment by mixtur** [comment]
Thank you for the issue.
Just published 0.1.2 that fixes it.
I used path.posix for retina.cssImageRef, and it seems to be working.
