### ISSUE TITLE
Support for image min

### ISSUE THREAD

**Issue by Truemedia** [mixtur/webpack-spritesmith#75]
https://www.npmjs.com/package/imagemin

Hi,
I used to use gulp spritesmith before webpack became quite standard as a build tool. In my old solution with the image and css streams I was able to pipe to compression plugins, the most crucial being imagemin.

With image min I was able to compress my sprite image to 10 times smaller space which is extremely useful when you have a massive sprite.

Would it be possible to add imagemin as an option and then also specify the plugin (pngquant is best for size but sometimes causes artifacts).

**Comment by mixtur** [comment]
If both your css and images are going through webpack you should easily be able to add imagemin to your pipeline.

Config in readme already already does that for you. You will only have to add something like https://www.npmjs.com/package/imagemin-webpack or https://www.npmjs.com/package/imagemin-webpack-plugin

**Comment by Truemedia** [comment]
@mixtur Ah ok, interesting I will give that a try thanks

**Comment by mixtur** [comment]
Closing dues to inactivity
