### ISSUE TITLE
add `sss` extension

### ISSUE THREAD

**Issue by Krasnopir** [mixtur/webpack-spritesmith#76]
Can you add .sss type 
Sugarss is custom syntax for PostCSS and many projects are switching to using PostCSS, so it would be wonderful to be able to import the right files.

**Comment by mixtur** [comment]
Target languages support is depending on https://github.com/twolfson/spritesheet-templates. So it first should be supported there.
Another option would be for you to write custom template.

**Comment by Krasnopir** [comment]
target: {
        ....
        css: [
            [
                path.resolve(__dirname, `/sources/sugarss/sprite.sss`),
                { format: 'sugarss_handlebars' }
            ]
        ]
    },
    customTemplates: {
        'sugarss_handlebars': path.resolve(__dirname, '/sources/sugarss/pngSpriteTemplate.handlebars')
    },

It works!)  Fine!)
