### ISSUE TITLE
Console output messages with created assets

### ISSUE THREAD

**Issue by Krasnopir** [mixtur/webpack-spritesmith#77]
Is there any way to get messages about successful assets creation(.png  and styles files)?
Ideally it would be with additional information - time, file size, etc.
Or at least something like
Files: '[path]/[name].png', '[path]/[name].[css/..]' was created success

**Comment by mixtur** [comment]
Added this in 0.5.4. Specify `logCreatedFiles: true` in options and it should work.

**Comment by Krasnopir** [comment]
thank you!
