### ISSUE TITLE
JSON export

### ISSUE THREAD

**Issue by Secretmapper** [mixtur/webpack-spritesmith#8]
It would be great if the plugin also supports JSON export.

**Comment by mixtur** [comment]
It does. Though in a little bit awkward way. You'll have to specify in config
```javascript
target: {
   css: '/path/to/file.json'
}
```
Is that what you meant? Or you want to export some css/stylus/sass AND json?

**Comment by mixtur** [comment]
Just fixed readme to be more clear about that.

**Comment by Secretmapper** [comment]
Awesome thanks! :)
