### ISSUE TITLE
How to optimise the sprite image?

### ISSUE THREAD

**Issue by majaray** [mixtur/webpack-spritesmith#82]
Hi,
I have many of png image files that want to convert into a single sprite image.
But I found the total size of the png files are less than the sprite image.
Sometimes it could be a huge different.
May I know is there any approach to optimise the exported sprite image?

Thank you!

**Comment by mixtur** [comment]
If you use file-loader as in README then you can also use whole universe of webpack plugins that will allow you to compress final image better.
Though it is possible that you still will not be able to achieve smaller size. If for example you have small pallettes in every source png, but overall pallette is large then it will be harder to compress combined image better than original.

**Comment by majaray** [comment]
i see, understood. 
thanks for your advise @mixtur!

**Comment by borm** [comment]
Up, can u show example please @mixtur ?
as i understood 
```
import ImageMinimizerPlugin from 'image-minimizer-webpack-plugin';
...
{ test: /\.png$/, use: ['file-loader?name=i/[hash].[ext]'] },
...
new ImageMinimizerPlugin({
      minimizerOptions: {
        // Lossless optimization with custom option
        // Feel free to experiment with options for better result for you
        plugins: [['optipng', { optimizationLevel: 5 }]],
      },
    }),
```
