### ISSUE TITLE
How to generate an animated sprite (GIF) out of animated GIFs?

### ISSUE THREAD

**Issue by EasterPeanut** [mixtur/webpack-spritesmith#85]
I can only get the generated GIF sprite to be static. Is there a way to have it animated?

**Comment by mixtur** [comment]
Never checked this. This may work though:
```js
new SpritesmithPlugin({
  target: {
    ...,
    image: path.resolve(__dirname, 'path/to/spritesheet.gif'
  },
  ...
  spritesmithOptions: {
    engine: require('gmsmith')
  }
})
```
If it will not work I don't think I'll be able to do anythinhg else.

**Comment by EasterPeanut** [comment]
> If it will not work I don't think I'll be able to do anythinhg else.

Hm, too bad, I tried that already, but this will render the layers of the animated gifs on top of each other in the generated sprite.

I guess it's not very common to generate animating sprites anyway tho

**Comment by mixtur** [comment]
I can imagine two reasons why you would want that.
- if you only want to reduce number of network requests, try css-loader + url-loader.
- if you want perfectly synced animation on hover or some other state change. I used this approach once. https://blog.teamtreehouse.com/css-sprite-sheet-animations-steps It could be generalized for multiple animations
