### ISSUE TITLE
Multiple plugin for generating multiple sprites from different source images causes problems

### ISSUE THREAD

**Issue by facinick** [mixtur/webpack-spritesmith#92]
If i use two plugin: 
new SpritesmithPlugin({})
new SpritesmithPlugin({})

the lower one overrides few options of upper one like Handle bar template location.

--------------------------actual code where this happened----------------------------------------
```
new SpritesmithPlugin({
            src: {
                cwd: imagesPath,
                glob: "**/*.{jpg,png}",
            },
            target: {
                image: path.resolve(__dirname, "..", "dist/images/") + "/sprite.png",
                // this file will be used to import and access sprites.png
                css: [
                    [
                        path.resolve(__dirname, "..", "src/app/styles/") + "/sprites.less",
                        { format: "handlebars_based_template" },
                    ],
                ],
            },
            apiOptions: {
                cssImageRef: "sprite.png",
            },
            customTemplates: {
                handlebars_based_template:
                    path.resolve(__dirname, "..", "src/app/images/") + "/handlebarsStr.css.handlebars",
            },
        }),

        new SpritesmithPlugin({
            src: {
                cwd: path.resolve(__dirname, "..", "src/app/thirdparty/bjnui/src/sprites"),
                glob: "**/*.{jpg,png}",
            },
            target: {
                image: path.resolve(__dirname, "..", "src/app/thirdparty/bjnui/src/images") + "/sprite.png",
                css: [
                    [
                        path.resolve(__dirname, "..", "src/app/thirdparty/bjnui/src/styles") + "/sprites.less",
                        {
                            format: "handlebars_based_template",
                        },
                    ],
                ],
            }, 
            apiOptions: {
                cssImageRef: "sprite.png",
            },
            customTemplates: {
                handlebars_based_template:
                    path.resolve(__dirname, "..", "src/app/thirdparty/bjnui/src/sprites") +
                    "/handlebarsStr.css.handlebars",
            },
        }),

```

**Comment by facinick** [comment]
How can I use this plugin to generate different sprites from different sources?

**Comment by mixtur** [comment]
Use different format names.

**Comment by facinick** [comment]
Can you please show me a small example how to? I am really new to even webapck.. I would be really grateful..
I understand the sprites concept but, how this plugin is to be used specially the "cssImageRef" part I am confused.

**Comment by facinick** [comment]
Oh I got the different format names, It's just an identifier right. Cool, so basically, wherever this plugin generates the ".less" output, I can import that less file into my other less and use by ".sprite() Directly right? will It also generate those sprite pngs in the output bundle? It should right?

**Comment by facinick** [comment]
Also what exactly is cssImageRef part?

**Comment by facinick** [comment]
> Oh I got the different format names, It's just an identifier right. Cool, so basically, wherever this plugin generates the ".less" output, I can import that less file into my other less and use by ".sprite() Directly right? will It also generate those sprite pngs in the output bundle? It should right?

actually it's not exactly doing that. It's all referencing fine now, but I cannot see sprite in final output bundle. Why so ?normally webpack should bindle all dependencies ( in this case sprite.png ) also in output right?

**Comment by facinick** [comment]
output: sprite.png
output: sprite.less ( has links to sprite.png file )

inside useSprite.less>>
@import "./sprites";
.closeButton() {
        .sprite(ic_cross1);
}

This should work right?

**Comment by facinick** [comment]
https://stackoverflow.com/questions/59420215/webpack-not-generating-sprites-png-file-in-output-bundle

I think the way I am referencing it or something isn't correct. It's generating the output less and png files.. how do I import it properly and link?

**Comment by facinick** [comment]
Thanks!
