### ISSUE TITLE
How to generate sprite image/s by folder structure?

### ISSUE THREAD

**Issue by marvin-aoanan** [mixtur/webpack-spritesmith#97]
How to generate sprite image/s by folder structure?
For example I want to generate a sprite images separately in each folder?
src
-folder1
--icon1.png
--icon2.png
--icon3.png
-folder2
--icon1.png
--icon2.png
--icon3.png

sample output:
spritesmith-generated
-sprite1.css
-sprite1.png 
-sprite2.css
-sprite2.png

**Comment by mixtur** [comment]
Create two plugin instances. There already was such issue https://github.com/mixtur/webpack-spritesmith/issues/19#issuecomment-261703943
